# Generated by Django 2.2.13 on 2021-05-14 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Untitled', max_length=200, unique=True)),
                ('photo', models.ImageField(upload_to='images')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(choices=[('missings', 'MISSINGS'), ('criminals', 'CRIMINALS')], default='home', max_length=7)),
                ('filter', models.CharField(choices=[('missings', 'MISSINGS'), ('criminals', 'CRIMINALS')], default='all', max_length=7)),
            ],
        ),
    ]
