# Generated by Django 2.2.13 on 2021-05-15 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recognize', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='category',
            field=models.CharField(choices=[('miss', 'MISSINGS'), ('crime', 'CRIMINALS')], default='home', max_length=7),
        ),
        migrations.AlterField(
            model_name='image',
            name='filter',
            field=models.CharField(choices=[('miss', 'MISSINGS'), ('crime', 'CRIMINALS')], default='all', max_length=7),
        ),
    ]
