# Generated by Django 3.1.8 on 2021-05-30 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recognize', '0004_auto_20210516_0426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageuploader',
            name='filter',
            field=models.CharField(choices=[('miss', 'MISSINGS'), ('crime', 'CRIMINALS'), ('mart', 'MARTYR')], default='all', max_length=7),
        ),
    ]
