# Generated by Django 3.1.7 on 2023-04-03 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recognize', '0005_auto_20210530_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageuploader',
            name='filter',
            field=models.CharField(choices=[('miss', 'MISSINGS'), ('crime', 'CRIMINALS'), ('mart', 'MARTYR')], default='miss', max_length=7),
        ),
    ]
